// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/about/about.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Header: typeof import('./src/components/header.vue')['default']
    ItemPhoto: typeof import('./src/components/project/project-item/item-photo.vue')['default']
    Loading: typeof import('./src/components/loading/loading.vue')['default']
    Main: typeof import('./src/components/main/main.vue')['default']
    MainContent: typeof import('./src/components/main/cpns/main-content.vue')['default']
    Project: typeof import('./src/components/project/project.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
